version: '3'

services:
  mysql:
    container_name: mysql
    image: "mysql:5.7"
    env_file: .env
    environment:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        SECRET_KEY: ${SECRET_KEY}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
        - "3307:3306"
    volumes:
        - ./.dbdata:/var/lib/mysql:rw
    networks:
        - backend
  devbook:
    container_name: devbook
    image: devbook
    env_file: .env
    environment:
      API_PORT: ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}/tcp"
      - "9000"
    depends_on:
      - mysql
    volumes:
      - .:/go/src/app
    networks:
      - backend

networks:
  backend:
    driver: bridge